name: Checkov

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Retrieve source code
       uses: actions/checkout@v2
     - name : Install checkov
       run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python3.7
          sudo apt install python3-pip
          sudo python3.7 -m pip install -U checkov 
     - name: Create results folder
       run: mkdir results
     - name : Scanning manifest folder
       run: checkov --directory manifests -o cli --quiet 2>&1 | tee -a ./results/checkov.txt
       continue-on-error: true
     - name: Upload artifact
       if: ${{ always() }}
       uses: actions/upload-artifact@v2
       with:
        path: ./results
        name: results                

  
