name: Dockle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name : Install Dockle
       run: |
          VERSION=$(
           curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
           grep '"tag_name":' | \
           sed -E 's/.*"v([^"]+)".*/\1/' \
          ) && curl -L -o dockle.deb https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb
          sudo dpkg -i dockle.deb && rm dockle.deb
     - name: Create results folder
       run: mkdir results
     - name : Scanning image
       run: dockle goodwithtech/test-image:v1 2>&1 | tee -a ./results/dockle.txt
     - name: Upload artifact
       if: ${{ always() }}
       uses: actions/upload-artifact@v3
       with:
        path: ./results
        name: results           
