name: Hadolint

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Retrieve source code
       uses: actions/checkout@v2
     #- uses: brpaz/hadolint-action@v1.2.1
     #  with:
     #    dockerfile: hadolint/Dockerfile
     #  continue-on-error: true
     - name : Scanning manifest folder
       run: docker run --rm -i ghcr.io/hadolint/hadolint < hadolint/Dockerfile > results.txt
       continue-on-error: true
     - name: Upload artifact
       if: ${{ always() }}
       uses: actions/upload-artifact@v2
       with:
        path: results.txt        
        name: results   
