name: Kubestriker

on:
  workflow_dispatch:
    inputs:
        CLUSTER_NAME:
          description: 'Cluster Name'     
          required: true
          default: 'aks-test'
        RESOURCE_GROUP:
          description: 'Resource Group' 
          required: true
          default: 'rg-demo-aks'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: AZ Login
        run: az login --service-principal -u ${{ secrets.AZ_LOGIN }} -p ${{ secrets.AZ_PASSWORD }} --tenant ${{ secrets.AZ_TENANT }}
        
      - name: Auth to k8s
        run: az aks get-credentials --name ${{ github.event.inputs.CLUSTER_NAME }} --resource-group ${{ github.event.inputs.RESOURCE_GROUP }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.8'
        
      - name: Config Pythong
        run: |
          python3 -m venv env
          source env/bin/activate
        
      - name: Install prompt-toolkit
        run: |
          python3 -m pip install prompt-toolkit==1.0.15  
          
      - name: Install SelectMenu
        run: |
          python3 -m pip install --pre SelectMenu==1.0.0b2
          
      - name: Install striker
        run: |
          python3 -m pip install kubestriker
      
      - name: Run striker
        run: |
          python -m kubestriker
          
