name: Kube-linter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Retrieve source code
       uses: actions/checkout@v2
     - run: kube-linter --help
     - name: Scan yamls
       id: kube-lint-scan
       uses: stackrox/kube-linter-action@v1
       with:
         directory: ./manifests/
     - name: Upload artifact
       uses: actions/upload-artifact@v2
       with:
        path: results.txt        
        name: results                

  
