name: kubescape.io
on:
  workflow_dispatch:
    inputs:
        CLUSTER_NAME:
          description: 'Cluster Name'     
          required: true
          default: 'aks-test'
        RESOURCE_GROUP:
          description: 'Resource Group' 
          required: true
          default: 'rg-demo-aks'
jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
      
      - name: AZ Login
        run: az login --service-principal -u ${{ secrets.AZ_LOGIN }} -p ${{ secrets.AZ_PASSWORD }} --tenant ${{ secrets.AZ_TENANT }}
        
      - name: Auth to k8s
        run: az aks get-credentials --name ${{ github.event.inputs.CLUSTER_NAME }} --resource-group ${{ github.event.inputs.RESOURCE_GROUP }}
        
      - name: Run kubescape scanner
        run: kubescape scan framework nsa --submit -o kubescape.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
         path: kubescape.txt
         name: results 
