name: kubescore

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Retrieve source code
       uses: actions/checkout@v2
     - name : Install kubescore
       run: |
          VERSION=$(
           curl --silent "https://api.github.com/repos/zegl/kube-score/releases/latest" | \
           grep '"tag_name":' | \
           sed -E 's/.*"v([^"]+)".*/\1/' \
          ) && curl -L -o kube-score https://github.com/zegl/kube-score/releases/download/v${VERSION}/kube-score_${VERSION}_linux_amd64

     - name: Create results folder
       run: mkdir results
     - name : Scanning manifest folder
       run: |
          ls -al
          kube-score score manifests/*.yaml 2>&1 | tee -a ./results/kube-score.txt
       continue-on-error: true
     - name: Upload artifact
       if: ${{ always() }}
       uses: actions/upload-artifact@v2
       with:
        path: ./results
        name: results                

  
