name: kubesec.io
on:
  workflow_dispatch:
jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@v0.0.2
        continue-on-error: true
        with:
          input: ./manifests/test.yaml
          output: kubesec.io.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
         path: kubesec.io.txt
         name: results 
