name: kubescore

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Retrieve source code
       uses: actions/checkout@v2
     - name: Create results folder
       run: mkdir results
     - name: kube-score action step
       uses: piraces/kube-score-ga@v0.1.2
       with:
         manifests-folders: './manifests/*.yaml'
         ignore-exit-code: 'true'
         output-file: './results/output.txt'
     - name: Upload artifact
       uses: actions/upload-artifact@v2
       with:
        path: ./results
        name: results                

  
