name: kubescore

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Retrieve source code
       uses: actions/checkout@v2
     - name : Install kubescore
       run: brew install kube-score/tap/kube-score
     - name: Setup tmate session
       uses: mxschmitt/action-tmate@v3
       timeout-minutes: 15
     - name: Create results folder
       run: mkdir results
     - name : Scanning manifest folder
       run: kube-score score manifests/*.yaml 2>&1 | tee -a ./results/kube-score.txt
       continue-on-error: true
     - name: Upload artifact
       if: ${{ always() }}
       uses: actions/upload-artifact@v2
       with:
        path: ./results
        name: results                

  
