name: Trivy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Retrieve source code
       uses: actions/checkout@v2
     - name : Install checkov
       run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python3.7
          sudo apt install python3-pip
          sudo python3.7 -m pip install -U checkov 
     - name: Run Trivy vulnerability scanner
       uses: aquasecurity/trivy-action@master
       with:
         image-ref: 'goodwithtech/test-image:v1'
         format: 'table'
         exit-code: ''
         ignore-unfixed: true
         output: '/results/results.txt'
         vuln-type: 'os,library'
         severity: 'CRITICAL,HIGH'
     - name: Upload artifact
       if: ${{ always() }}
       uses: actions/upload-artifact@v2
       with:
        path: /results      
        name: results-trivy   
