name: Trivy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Retrieve source code
       uses: actions/checkout@v5
     - name: Create results folder
       run: mkdir results
     - name: Run Trivy vulnerability scanner
       uses: aquasecurity/trivy-action@master
       with:
         image-ref: 'goodwithtech/test-image:v1'
         format: 'table'
         exit-code: ''
         ignore-unfixed: true
         output: './results/trivy.txt'
         vuln-type: 'os,library'
         severity: 'CRITICAL,HIGH'
     - name: Upload artifact
       if: ${{ always() }}
       uses: actions/upload-artifact@v4
       with:
        path: ./results      
        name: results   
